version: '3.8'

services:
  traefik:
    # container_name: API-Gateway-Trafeik
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - microservices-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nodejs-microservice:
    # container_name: Microservice-Nodejs
    build:
      context: ./nodejs-microservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodejs-microservice.rule=Host(`nodejs-microservice.localhost`)"
      - "traefik.http.routers.nodejs-microservice.entrypoints=web"
      - "traefik.http.services.nodejs-microservice.loadbalancer.server.port=3000"    
      - "traefik.http.routers.nodejs-microservice.service=nodejs-microservice"
      - "traefik.http.services.nodejs-microservice.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.nodejs-microservice.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.nodejs-microservice.loadbalancer.healthcheck.timeout=10s"

    networks:
      - microservices-network

  python-flask-microservice:
    # container_name: Microservice-python-flask
    build:
      context: ./python-flask-microservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python-flask-microservice.rule=Host(`python-flask-microservice.localhost`)"
      - "traefik.http.routers.python-flask-microservice.entrypoints=web"
      - "traefik.http.services.python-flask-microservice.loadbalancer.server.port=5000"    
      - "traefik.http.routers.python-flask-microservice.service=python-flask-microservice"
      - "traefik.http.services.python-flask-microservice.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.python-flask-microservice.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.python-flask-microservice.loadbalancer.healthcheck.timeout=10s"

    networks:
      - microservices-network

  non-web-service:
    build:
      context: ./non-web-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.non-web-service_router.rule=HostSNI(`*`)"
      # - "traefik.tcp.routers.non-web-service_router.entrypoints=web"
      - "traefik.tcp.services.non-web-service.loadbalancer.server.port=3000"

    networks:
      - microservices-network

networks:
  microservices-network:
