version: '3.8'

services:
  traefik:
    # container_name: API-Gateway-Trafeik
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.tcp.address=:30000"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - microservices-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nodejs-microservice:
    # container_name: Microservice-Nodejs
    build:
      context: ./nodejs-microservice
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodejs-microservice-router.rule=Host(`microservices-poc.localhost`) && PathPrefix(`/nodejs`)"
      - "traefik.http.routers.nodejs-microservice-router.entrypoints=web"
      - "traefik.http.routers.nodejs-microservice-router.service=nodejs-microservice"
      - "traefik.http.routers.nodejs-microservice-router.middlewares=strip-nodejs"
      - "traefik.http.middlewares.strip-nodejs.stripprefix.prefixes=/nodejs"
      - "traefik.http.services.nodejs-microservice.loadbalancer.server.port=3000"    
      - "traefik.http.services.nodejs-microservice.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.nodejs-microservice.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.nodejs-microservice.loadbalancer.healthcheck.timeout=10s"
    networks:
      - microservices-network

  python-flask-microservice:
    # container_name: Microservice-python-flask
    build:
      context: ./python-flask-microservice
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.python-flask-microservice-router.rule=Host(`microservices-poc.localhost`) && PathPrefix(`/python`)"
      - "traefik.http.routers.python-flask-microservice-router.entrypoints=web"
      - "traefik.http.routers.python-flask-microservice-router.service=python-flask-microservice"
      - "traefik.http.routers.python-flask-microservice-router.middlewares=strip-python"
      - "traefik.http.middlewares.strip-python.stripprefix.prefixes=/python"
      - "traefik.http.services.python-flask-microservice.loadbalancer.server.port=5000"    
      - "traefik.http.services.python-flask-microservice.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.python-flask-microservice.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.python-flask-microservice.loadbalancer.healthcheck.timeout=10s"
    networks:
      - microservices-network

  non-web-service:
    build:
      context: ./non-web-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.non-web-service_router.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.non-web-service_router.entrypoints=tcp"
      - "traefik.tcp.services.non-web-service.loadbalancer.server.port=30001"
    networks:
      - microservices-network

networks:
  microservices-network:
